// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    
    apiKey: 'AIzaSyATV5H7CW4ryNnauRhCDCnDths1lktBaEw',
    appId: '1:512840662244:web:ac3dbe2a29e344440e40f1',
    messagingSenderId: '512840662244',
    projectId: 'resqmap-b2ed5',
    authDomain: 'resqmap-b2ed5.firebaseapp.com',
    storageBucket: 'resqmap-b2ed5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNDwLN9QLVgXzAKcvEvABtlK6ZBUwxVY',
    appId: '1:512840662244:android:73e63bbf2c4cfcd70e40f1',
    messagingSenderId: '512840662244',
    projectId: 'resqmap-b2ed5',
    storageBucket: 'resqmap-b2ed5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAFfoSHK4LCsOFqsukrY5OtkZg7fo9DkQ',
    appId: '1:512840662244:ios:4a4cf1f2b2110cd00e40f1',
    messagingSenderId: '512840662244',
    projectId: 'resqmap-b2ed5',
    storageBucket: 'resqmap-b2ed5.firebasestorage.app',
    iosBundleId: 'com.example.resqMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAFfoSHK4LCsOFqsukrY5OtkZg7fo9DkQ',
    appId: '1:512840662244:ios:4a4cf1f2b2110cd00e40f1',
    messagingSenderId: '512840662244',
    projectId: 'resqmap-b2ed5',
    storageBucket: 'resqmap-b2ed5.firebasestorage.app',
    iosBundleId: 'com.example.resqMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATV5H7CW4ryNnauRhCDCnDths1lktBaEw',
    appId: '1:512840662244:web:8e872758406cdf960e40f1',
    messagingSenderId: '512840662244',
    projectId: 'resqmap-b2ed5',
    authDomain: 'resqmap-b2ed5.firebaseapp.com',
    storageBucket: 'resqmap-b2ed5.firebasestorage.app',
  );
}
